Torres_de_Hanoi: PilhaEncadeada::Pilha Class Reference
PilhaEncadeada::Pilha Class Reference
#include <Pilha.h>
Public Member Functions
Pilha ()
virtual ~Pilha ()
int empilha (Disco *novo)
Disco * desempilha ()
bool vazia ()
bool contem (Disco *examinado)
Public Attributes
Disco * topo
int id
int tamanho
int diametroTopo
Detailed Description
Classe para representação de estruturas de dados Pilha.
As pilhas são estruturas baseadas no princípio LIFO (last in, first out), na qual os dados que foram inseridos primeiros na pilha serão os últimos a serem removidos. Existem duas funções que se aplicam a todas as pilhas: EMPILHA (PUSH), que insere um dado no topo da pilha, e DESEMPILHAR (POP), que remove o item no topo da pilha.
Definition at line 37 of file Pilha.h.
Constructor & Destructor Documentation
PilhaEncadeada::Pilha::Pilha ()
Construtor que configura um objeto da classe Pilha que inicializa tudo em 0;
Definition at line 15 of file Pilha.cpp.
References diametroTopo, tamanho, and topo.
PilhaEncadeada::Pilha::~Pilha () [virtual]
Destrutor que exclui um objeto da classe Pilha
Definition at line 24 of file Pilha.cpp.
Member Function Documentation
bool PilhaEncadeada::Pilha::contem (Disco * examinado)
Método que verifica se um objeto Disco está ou nao na pilha.
Parameters:
*examinado = ponteiro para um objeto do tipo Disco.
Returns:
true caso o ponteiro esteje contido.
Definition at line 97 of file Pilha.cpp.
References PilhaEncadeada::Disco::proximo, and topo.
Referenced by PilhaEncadeada::TorresDeHanoi::moverMenor().
Disco * PilhaEncadeada::Pilha::desempilha ()
Método que retira o ultimo elemento pilha.
Para isso ele verifica se a pilha esta vazia. Caso não esteja, retira o elemento que esta no topo da pilha(ultima poscição), atualiza o topo e o diametro do Topo(caso acabe vazia o diametro será considerado zero), e o retorna para ser usado.
Returns:
PILHA_VAZIA = caso a pilha em execução esteja vazia, será retornado o codigo de erro PILHA_VAZIA.
Ponteiro para um objeto do tipo Disco que está na ultima posição da Pilha.
Definition at line 68 of file Pilha.cpp.
References PilhaEncadeada::Disco::diametro, diametroTopo, id, PilhaEncadeada::Disco::origem, PILHA_VAZIA, PilhaEncadeada::Disco::proximo, tamanho, topo, and vazia().
Referenced by PilhaEncadeada::TorresDeHanoi::fazerJogadaSeguinte(), PilhaEncadeada::TorresDeHanoi::moverMenor(), PilhaEncadeada::TorresDeHanoi::resolverImpar(), and PilhaEncadeada::TorresDeHanoi::resolverPar().
int PilhaEncadeada::Pilha::empilha (Disco * novo)
Método que adiciona um ponteiro para um objeto Disco.
Para isso verifica se o ponteiro é valido. Também verifica se a lista está vazia.Caso a questão anterior seja verdadeira o objeto é adicionado na primeira posição da Lista.Caso seja falsa é adicionado na posição seguinte a da ultima.
Parameters:
*novo = ponteiro para um objeto do tipo Disco que tentará ser adicionado na pilha.
Returns:
ERRO_MOVIMENTO = caso o Disco em uso não seja válido será retornado o numero de codigo de erro: ERRO_MOVIMENTO.
0 (inteiro zero) = caso o objeto tenha sido adicionado com sucesso.
Definition at line 40 of file Pilha.cpp.
References PilhaEncadeada::Disco::diametro, diametroTopo, ERRO_MOVIMENTO, PilhaEncadeada::Disco::origem, PilhaEncadeada::Disco::proximo, tamanho, topo, and vazia().
Referenced by PilhaEncadeada::TorresDeHanoi::fazerJogadaSeguinte(), PilhaEncadeada::TorresDeHanoi::moverMenor(), PilhaEncadeada::TorresDeHanoi::resolverImpar(), PilhaEncadeada::TorresDeHanoi::resolverPar(), and PilhaEncadeada::TorresDeHanoi::TorresDeHanoi().
bool PilhaEncadeada::Pilha::vazia ()
Método que compara a variavel tamanho com a constante LISTA_VAZIA.
Returns:
true se a pilha estiver vazia.
Definition at line 87 of file Pilha.cpp.
References PILHA_VAZIA, and tamanho.
Referenced by desempilha(), and empilha().
Member Data Documentation
int PilhaEncadeada::Pilha::diametroTopo
Definition at line 44 of file Pilha.h.
Referenced by desempilha(), empilha(), PilhaEncadeada::TorresDeHanoi::fazerJogadaSeguinte(), and Pilha().
int PilhaEncadeada::Pilha::id
Definition at line 42 of file Pilha.h.
Referenced by desempilha(), and PilhaEncadeada::TorresDeHanoi::TorresDeHanoi().
int PilhaEncadeada::Pilha::tamanho
Definition at line 43 of file Pilha.h.
Referenced by desempilha(), empilha(), PilhaEncadeada::TorresDeHanoi::fazerJogadaSeguinte(), Pilha(), PilhaEncadeada::TorresDeHanoi::resolverImpar(), PilhaEncadeada::TorresDeHanoi::resolverPar(), and vazia().
Disco* PilhaEncadeada::Pilha::topo
Definition at line 41 of file Pilha.h.
Referenced by contem(), desempilha(), empilha(), and Pilha().
The documentation for this class was generated from the following files:
/home/will/Programming/C++/ED/Torres_de_Hanoi/src/Pilha.h
/home/will/Programming/C++/ED/Torres_de_Hanoi/src/Pilha.cpp