Torres_de_Hanoi: PilhaEncadeada::TorresDeHanoi Class Reference
PilhaEncadeada::TorresDeHanoi Class Reference
#include <TorresDeHanoi.h>
Public Member Functions
TorresDeHanoi ()
TorresDeHanoi (int total)
virtual ~TorresDeHanoi ()
void iniciarJogadas ()
Private Member Functions
void resolverPar ()
void resolverImpar ()
void moverMenor ()
void fazerJogadaSeguinte ()
Private Attributes
Pilha fonte
Pilha meio
Pilha destino
Disco * menor
int totalDiscos
int posMenor
Detailed Description
Definition at line 50 of file TorresDeHanoi.h.
Constructor & Destructor Documentation
PilhaEncadeada::TorresDeHanoi::TorresDeHanoi ()
Construtor que configura um objeto da classe TorresDeHanoi inicializando totalDiscos em 0.
Definition at line 15 of file TorresDeHanoi.cpp.
References totalDiscos.
PilhaEncadeada::TorresDeHanoi::TorresDeHanoi (int total)
Construtor que configura um objeto da classe TorresDeHanoi, inicializando posMenor em 1, e atribuindo as ID às suas respectivas pilhas.
Parameters:
total = valor inteiro que contem a quantidade de discos que devem ser criados na pilha fonte.
Definition at line 24 of file TorresDeHanoi.cpp.
References destino, PilhaEncadeada::Pilha::empilha(), fonte, PilhaEncadeada::Pilha::id, ID_DESTINO, ID_FONTE, ID_MEIO, meio, posMenor, and totalDiscos.
PilhaEncadeada::TorresDeHanoi::~TorresDeHanoi () [virtual]
Destrutor que exclui um objeto da classe TorresDeHanoi
Definition at line 41 of file TorresDeHanoi.cpp.
Member Function Documentation
void PilhaEncadeada::TorresDeHanoi::fazerJogadaSeguinte () [private]
Método que faz a desição de qual deve ser o proximo movimento do Disco no caso em que não é a vez do menor e que ja foi efetuada uma jogada com o menor.
Para isto, verifica em qual pino se encontra o Disco menor e verifica qual é o maior diametroTopo dos outros dois pinos. Uma vez decidido, desempilha o Disco do pino com menor diametroTopo e o coloca no pino com maior diametroTopo.
Definition at line 52 of file TorresDeHanoi.cpp.
References PilhaEncadeada::Pilha::desempilha(), destino, PilhaEncadeada::Pilha::diametroTopo, PilhaEncadeada::Pilha::empilha(), fonte, meio, posMenor, PilhaEncadeada::Pilha::tamanho, and totalDiscos.
Referenced by resolverImpar(), and resolverPar().
void PilhaEncadeada::TorresDeHanoi::iniciarJogadas ()
Método que verifica se o numero total de Discos que esta contido na variável totalDiscos, é par ou não.
Para logo fazer a decisão de chamar o metodo resolverPar(), caso seja par. Ou resolverImpar(), caso seja impar.
Definition at line 186 of file TorresDeHanoi.cpp.
References resolverImpar(), resolverPar(), and totalDiscos.
Referenced by main().
void PilhaEncadeada::TorresDeHanoi::moverMenor () [private]
Método que faz a desição de qual deve ser o movimento do Disco menor, no caso em que não é mais a primeira jogada.
Para isto, verifica em qual pino se encontra o Disco menor e qual é sua origem.
Definition at line 103 of file TorresDeHanoi.cpp.
References PilhaEncadeada::Pilha::contem(), PilhaEncadeada::Pilha::desempilha(), destino, PilhaEncadeada::Pilha::empilha(), fonte, ID_DESTINO, ID_FONTE, ID_MEIO, meio, menor, PilhaEncadeada::Disco::origem, and posMenor.
Referenced by resolverImpar(), and resolverPar().
void PilhaEncadeada::TorresDeHanoi::resolverImpar () [private]
Método que faz a resolução do jogo no caso em que o numero total de Discos em jogo é impar. Faz um movimento do Disco menor para o pino destino na primeira jogada, depois chama o metodo fazerJogadaSeguinte() para mover outra peça que não seja a menor, e depois faz mais um movimento da menor, com o metodo moverMenor(). Isto se repete até o fim do jogo, quando todos os Discos estão no pino destino
Definition at line 168 of file TorresDeHanoi.cpp.
References PilhaEncadeada::Pilha::desempilha(), destino, PilhaEncadeada::Pilha::empilha(), fazerJogadaSeguinte(), fonte, ID_DESTINO, menor, moverMenor(), posMenor, PilhaEncadeada::Pilha::tamanho, and totalDiscos.
Referenced by iniciarJogadas().
void PilhaEncadeada::TorresDeHanoi::resolverPar () [private]
Método que faz a resolução do jogo no caso em que o numero total de Discos em jogo é par. Faz um movimento do Disco menor para o pino do meio na primeira jogada, depois chama o metodo fazerJogadaSeguinte() para mover outra peça que não seja a menor, e depois faz mais um movimento da menor, com o metodo moverMenor(). Isto se repete até o fim do jogo, quando todos os Discos estão no pino destino
Definition at line 148 of file TorresDeHanoi.cpp.
References PilhaEncadeada::Pilha::desempilha(), destino, PilhaEncadeada::Pilha::empilha(), fazerJogadaSeguinte(), fonte, ID_MEIO, meio, menor, moverMenor(), posMenor, PilhaEncadeada::Pilha::tamanho, and totalDiscos.
Referenced by iniciarJogadas().
Member Data Documentation
Pilha PilhaEncadeada::TorresDeHanoi::destino [private]
Definition at line 59 of file TorresDeHanoi.h.
Referenced by fazerJogadaSeguinte(), moverMenor(), resolverImpar(), resolverPar(), and TorresDeHanoi().
Pilha PilhaEncadeada::TorresDeHanoi::fonte [private]
Definition at line 57 of file TorresDeHanoi.h.
Referenced by fazerJogadaSeguinte(), moverMenor(), resolverImpar(), resolverPar(), and TorresDeHanoi().
Pilha PilhaEncadeada::TorresDeHanoi::meio [private]
Definition at line 58 of file TorresDeHanoi.h.
Referenced by fazerJogadaSeguinte(), moverMenor(), resolverPar(), and TorresDeHanoi().
Disco* PilhaEncadeada::TorresDeHanoi::menor [private]
Definition at line 60 of file TorresDeHanoi.h.
Referenced by moverMenor(), resolverImpar(), and resolverPar().
int PilhaEncadeada::TorresDeHanoi::posMenor [private]
Definition at line 62 of file TorresDeHanoi.h.
Referenced by fazerJogadaSeguinte(), moverMenor(), resolverImpar(), resolverPar(), and TorresDeHanoi().
int PilhaEncadeada::TorresDeHanoi::totalDiscos [private]
Definition at line 61 of file TorresDeHanoi.h.
Referenced by fazerJogadaSeguinte(), iniciarJogadas(), resolverImpar(), resolverPar(), and TorresDeHanoi().
The documentation for this class was generated from the following files:
/home/will/Programming/C++/ED/Torres_de_Hanoi/src/TorresDeHanoi.h
/home/will/Programming/C++/ED/Torres_de_Hanoi/src/TorresDeHanoi.cpp