SimuladorDeSupermercado: Projeto1::Cliente Class Reference
Projeto1::Cliente Class Reference
#include <Cliente.h>
Public Member Functions
Cliente ()
Cliente (int chegada)
virtual ~Cliente ()
void gerarTotalDeCompras ()
void calcularValorDeCompras ()
void decidirCheque ()
Public Attributes
int totalCompras
int valorCompras
int chegada
int saida
bool cheque
TipoCliente tipo
Detailed Description
Definition at line 20 of file Cliente.h.
Constructor & Destructor Documentation
Projeto1::Cliente::Cliente ()
Definition at line 14 of file Cliente.cpp.
References calcularValorDeCompras(), chegada, decidirCheque(), gerarTotalDeCompras(), saida, and valorCompras.
Projeto1::Cliente::Cliente (int chegada)
Definition at line 23 of file Cliente.cpp.
References calcularValorDeCompras(), chegada, decidirCheque(), gerarTotalDeCompras(), saida, and valorCompras.
Projeto1::Cliente::~Cliente () [virtual]
Definition at line 33 of file Cliente.cpp.
Member Function Documentation
void Projeto1::Cliente::calcularValorDeCompras ()
Método que calcula o valor de cada compra do cliente.
Para isso ele usa o metodo "rand()", que gera um numero aleatório,e delimita o intervalo de geração entre as constantes: MAX_VALOR e MIN_VALOR.
Definition at line 56 of file Cliente.cpp.
References MAX_VALOR, MIN_VALOR, totalCompras, and valorCompras.
Referenced by Cliente().
void Projeto1::Cliente::decidirCheque ()
Método que gera a forma de pagamento de um cliente.
Para isso tem uma probabilidade de 20% para pagamento em cheque e 80% para dinheiro.
Definition at line 72 of file Cliente.cpp.
References cheque, and PROB_CHEQUE.
Referenced by Cliente().
void Projeto1::Cliente::gerarTotalDeCompras ()
Método que fornece o lucro gerado pelo caixa durante a simulação.
Para tal fornecimento ele subtrai seu sálario, que é dobrado pois ele está em hora extra, de seu faturamento total.
Returns:
lucro gerado pelo caixa.
Definition at line 44 of file Cliente.cpp.
References MAX_COMPRAS, MAX_VALOR, MIN_COMPRAS, MIN_VALOR, and totalCompras.
Referenced by Cliente().
Member Data Documentation
int Projeto1::Cliente::chegada
horario de chegada do cliente
Definition at line 30 of file Cliente.h.
Referenced by Cliente(), and Projeto1::Caixa::receberCliente().
bool Projeto1::Cliente::cheque
True quando for pagamento em cheque
Definition at line 34 of file Cliente.h.
Referenced by decidirCheque(), and Projeto1::Caixa::receberCliente().
int Projeto1::Cliente::saida
horario de saida do cliente
Definition at line 32 of file Cliente.h.
Referenced by Cliente(), and Projeto1::Caixa::receberCliente().
TipoCliente Projeto1::Cliente::tipo
enum de tipo do cliente
Definition at line 36 of file Cliente.h.
Referenced by Projeto1::Supermercado::gerarCliente(), and Projeto1::Supermercado::posicionarCliente().
int Projeto1::Cliente::totalCompras
entre 2 e 100
Definition at line 26 of file Cliente.h.
Referenced by calcularValorDeCompras(), gerarTotalDeCompras(), and Projeto1::Caixa::receberCliente().
int Projeto1::Cliente::valorCompras
cada item varia entre 1 e 90r$ dai td junto é colocado aqui
Definition at line 28 of file Cliente.h.
Referenced by calcularValorDeCompras(), Cliente(), and Projeto1::Supermercado::posicionarCliente().
The documentation for this class was generated from the following files:
/home/will/Programming/C++/ED/Projeto 1/src/Cliente.h
/home/will/Programming/C++/ED/Projeto 1/src/Cliente.cpp