SimuladorDeSupermercado: Projeto1::Caixa Class Reference
Projeto1::Caixa Class Reference
#include <Caixa.h>
Public Member Functions
Caixa (char *nome, int eficiencia, int salario)
Caixa ()
virtual ~Caixa ()
int enfileirar (Cliente *dado)
Cliente * desenfileirar ()
void limpar ()
int receberCliente (Cliente *cliente)
virtual int fornecaLucro ()
long int atenderCliente (int horaAtual)
void mostrar ()
void apresentarRelatorio ()
Public Attributes
char * nomeCaixa
int eficiencia
int salario
int clientesAtendidos
int tempoMedio
int faturamentoTotal
ElementoDeFila * primeiro
ElementoDeFila * ultimo
int tamanhoFila
int totalProdutos
Private Member Functions
bool vazia ()
Detailed Description
Classe que representa um caixa de um supermercado.
Definition at line 24 of file Caixa.h.
Constructor & Destructor Documentation
Projeto1::Caixa::Caixa (char * nome, int eficienc, int salari)
Construtor que gera um caixa de supermercado.
Parameters:
nome : nome do operador do caixa.
eficienc : eficiencia do operador do caixa.
salari : salario do operador do caixa.
Definition at line 20 of file Caixa.cpp.
Projeto1::Caixa::Caixa ()
Definition at line 33 of file Caixa.cpp.
Projeto1::Caixa::~Caixa () [virtual]
Destrutor que exclui um objeto da classe caixa.
Definition at line 49 of file Caixa.cpp.
Member Function Documentation
void Projeto1::Caixa::apresentarRelatorio ()
Método que gera o relatório final da execução.
Definition at line 212 of file Caixa.cpp.
Referenced by Projeto1::Supermercado::apresentarResultados().
long int Projeto1::Caixa::atenderCliente (int horaAtual)
Método que verificar se o proximo cliente da fila deve ser atendimento.
Parameters:
horaAtual : instante em que se encontra o programa.
Returns:
Cliente : cliente que foi atendido.
Definition at line 193 of file Caixa.cpp.
Referenced by Projeto1::Supermercado::atenderClientes().
Cliente * Projeto1::Caixa::desenfileirar ()
Método que remove um elemento da Fila. Primeiramente testa se a Fila possui elementos. Caso possua ele remove o primeiro elemento, ou seja o primeiro que foi inserido.
Returns:
0(NULL) = caso a Fila não possua elementos.
volta = ponteiro para um objeto da classe cliente.
Definition at line 101 of file Caixa.cpp.
References Projeto1::ElementoDeFila::cliente, FILA_VAZIA, and Projeto1::ElementoDeFila::proximo.
int Projeto1::Caixa::enfileirar (Cliente * dado)
Método que adiciona um elemento da fila.
Primeiramente teste se ainda é possivel adicionar um elemento à fila. Caso isso não seja verdadeiro ele retorna uma constante FILA_CHEIA.
Parameters:
dado = ponteiro para um objeto da classe Cliente.
Returns:
FILA_CHEIA = constante que representa a falta de espaço na Fila.
tamanho = inteiro que informa a posição onde o dado foi inserido.
Definition at line 63 of file Caixa.cpp.
References FILA_CHEIA, and Projeto1::ElementoDeFila::proximo.
int Projeto1::Caixa::fornecaLucro () [virtual]
Método que fornece o lucro gerado pelo caixa corrente.
Returns:
lucro : ineiro.
Reimplemented in Projeto1::CaixaEspecial.
Definition at line 175 of file Caixa.cpp.
Referenced by Projeto1::Supermercado::apresentarResultados().
void Projeto1::Caixa::limpar ()
Método que exclui todos os elementos da fila e suas respectivas informações, representado pela classe Cliente.
Definition at line 122 of file Caixa.cpp.
References Projeto1::ElementoDeFila::cliente, FILA_VAZIA, and Projeto1::ElementoDeFila::proximo.
void Projeto1::Caixa::mostrar ()
Método que imprime as informações do caixa.
Definition at line 82 of file Caixa.cpp.
int Projeto1::Caixa::receberCliente (Cliente * cliente)
Método que calcula o tempo de saida de um cliente de acordo com seus parâmetros e com a eficoência do caixa.
Parameters:
cliente : cliente do supermercado.
Definition at line 140 of file Caixa.cpp.
References Projeto1::Cliente::chegada, Projeto1::Cliente::cheque, Projeto1::Cliente::saida, and Projeto1::Cliente::totalCompras.
Referenced by Projeto1::Supermercado::posicionarCliente().
bool Projeto1::Caixa::vazia () [private]
Metodo que testa se a fila possui elementos.
Returns:
true = caso a Fila esteja vazia.
Definition at line 90 of file Caixa.cpp.
References FILA_VAZIA.
Member Data Documentation
int Projeto1::Caixa::clientesAtendidos
numero de clientes atendidos
Definition at line 37 of file Caixa.h.
Referenced by Projeto1::Supermercado::apresentarResultados().
int Projeto1::Caixa::eficiencia
eficiencia do caixa
Definition at line 33 of file Caixa.h.
int Projeto1::Caixa::faturamentoTotal
faturamento total
Definition at line 41 of file Caixa.h.
Referenced by Projeto1::Supermercado::apresentarResultados(), and Projeto1::CaixaEspecial::fornecaLucro().
char* Projeto1::Caixa::nomeCaixa
identificador do caixa
Definition at line 31 of file Caixa.h.
ElementoDeFila* Projeto1::Caixa::primeiro
FilaDeClientes
Definition at line 45 of file Caixa.h.
int Projeto1::Caixa::salario
salario do caixa
Definition at line 35 of file Caixa.h.
Referenced by Projeto1::CaixaEspecial::fornecaLucro().
int Projeto1::Caixa::tamanhoFila
tamanho fila de clientes
Definition at line 49 of file Caixa.h.
Referenced by Projeto1::Supermercado::chamarCaixaEspecial(), and Projeto1::Supermercado::posicionarCliente().
int Projeto1::Caixa::tempoMedio
tempo medio de espera
Definition at line 39 of file Caixa.h.
int Projeto1::Caixa::totalProdutos
soma de todas as mercadorias dos clientes que estão na fila.
Definition at line 51 of file Caixa.h.
Referenced by Projeto1::Supermercado::posicionarCliente().
ElementoDeFila* Projeto1::Caixa::ultimo
FilaDeClientes
Definition at line 47 of file Caixa.h.
The documentation for this class was generated from the following files:
/home/will/Programming/C++/ED/Projeto 1/src/Caixa.h
/home/will/Programming/C++/ED/Projeto 1/src/Caixa.cpp