SimuladorDeSupermercado: Projeto1::Supermercado Class Reference
Projeto1::Supermercado Class Reference
#include <Supermercado.h>
Public Member Functions
Supermercado ()
Supermercado (ListaCircular *caixas, int tempClientes, int tempoTotal)
virtual ~Supermercado ()
void iniciarSimulacao ()
Cliente * gerarCliente (int horario)
int posicionarCliente (Cliente *novo)
int atenderClientes (int horario)
void chamarCaixaEspecial ()
void configurarSimulacao (char *nome, int tempoSimulacao, int tempoMedioChegada, int limiteCaixaEspecial, ListaCircular *caixas)
void apresentarResultados ()
Public Attributes
ListaCircular * caixas
char * nomeSupermercado
int tempoMedioClientes
int tempoSimulacao
int desistencias
int faturamentoBruto
int valorDesistencias
int limiteCaixaEspecial
bool caixaEspecialchamado
Detailed Description
Definition at line 15 of file Supermercado.h.
Constructor & Destructor Documentation
Projeto1::Supermercado::Supermercado ()
Costrutor que gera um objeto da classe supermercado.
Definition at line 21 of file Supermercado.cpp.
References caixas, limiteCaixaEspecial, and tempoSimulacao.
Projeto1::Supermercado::Supermercado (ListaCircular * c, int tempClientes, int tempoTotal)
Costrutor que gera um objeto da classe supermercado.
Parameters:
c : Pponteiro para Lista Circular de caixas do supermercado.
tempClientes : Tempo médio de chegada de clientes.
tempoTotal : Tempo total da simulação.
Definition at line 37 of file Supermercado.cpp.
References caixas, limiteCaixaEspecial, and tempoSimulacao.
Projeto1::Supermercado::~Supermercado () [virtual]
Definition at line 46 of file Supermercado.cpp.
Member Function Documentation
void Projeto1::Supermercado::apresentarResultados ()
Método que gera os resultados finais da execução.
Definition at line 198 of file Supermercado.cpp.
References Projeto1::Caixa::apresentarRelatorio(), Projeto1::ElementoDeListaCircular::caixa, caixas, Projeto1::Caixa::clientesAtendidos, Projeto1::Caixa::faturamentoTotal, Projeto1::Caixa::fornecaLucro(), nomeSupermercado, Projeto1::ElementoDeListaCircular::proximo, Projeto1::ListaCircular::sentinela, Projeto1::ListaCircular::tamanho, and tempoSimulacao.
Referenced by main().
int Projeto1::Supermercado::atenderClientes (int horario)
Método que atended um cliente.
Para isso ele percorre todos os caixas e verifica se o primeiro cliente da fila deve ser atendido, ou seja, se o tempo de saida desse cliente é igual ao tempo atual de execução.
Parameters:
horario : hora atual de execução.
Definition at line 162 of file Supermercado.cpp.
References Projeto1::Caixa::atenderCliente(), Projeto1::ElementoDeListaCircular::caixa, caixas, Projeto1::ElementoDeListaCircular::proximo, and Projeto1::ListaCircular::sentinela.
void Projeto1::Supermercado::chamarCaixaEspecial ()
Método que chama (constrói) um caixa do tipo caixa expecial.
Definition at line 174 of file Supermercado.cpp.
References Projeto1::ListaCircular::adiciona(), Projeto1::ElementoDeListaCircular::caixa, caixas, limiteCaixaEspecial, Projeto1::ElementoDeListaCircular::proximo, Projeto1::ListaCircular::sentinela, and Projeto1::Caixa::tamanhoFila.
void Projeto1::Supermercado::configurarSimulacao (char * nome, int tempoS, int tempoMedioC, int limiteCaixaEsp, ListaCircular * c)
Método que configura a simulação.
Parameters:
nome : nome do supermercado.
tempoS : tempo de simulação.
tempoMedioC : tempo médio de chegada de clientes.
limiteCaixaEsp,: limite de todas as filas antes de chamar o Caixa Especial
c : lista de caixas;
Definition at line 58 of file Supermercado.cpp.
References caixas, limiteCaixaEspecial, nomeSupermercado, and tempoSimulacao.
Referenced by main().
Cliente * Projeto1::Supermercado::gerarCliente (int horario)
Método que gera um cliente do supremercado, decidindo o tipo do mesmo.
Existem dois tipos de clientes, os que buscam a fila com menos clientes e os que buscam uma fila com menor numero de produtos dos outros clientes.
Definition at line 97 of file Supermercado.cpp.
References Projeto1::BuscaFilaComMenosProdutos, Projeto1::BuscaMenorFila, and Projeto1::Cliente::tipo.
void Projeto1::Supermercado::iniciarSimulacao ()
Método que executa a simulação.
Para isso percorre segundo a segundo executando os passos da simulação.
Definition at line 71 of file Supermercado.cpp.
References tempoSimulacao.
Referenced by main().
int Projeto1::Supermercado::posicionarCliente (Cliente * novo)
Método que posiciona um cliente na fila de um caixa, de acordo com seu tipo.
Parameters:
novo : Cliente a ser posicionado.
Definition at line 111 of file Supermercado.cpp.
References Projeto1::BuscaFilaComMenosProdutos, Projeto1::BuscaMenorFila, Projeto1::ElementoDeListaCircular::caixa, caixas, FATOR_IRRITACAO, MAX_CAIXA, Projeto1::ElementoDeListaCircular::proximo, Projeto1::Caixa::receberCliente(), Projeto1::ListaCircular::sentinela, Projeto1::Caixa::tamanhoFila, Projeto1::Cliente::tipo, Projeto1::Caixa::totalProdutos, and Projeto1::Cliente::valorCompras.
Member Data Documentation
bool Projeto1::Supermercado::caixaEspecialchamado
Informação se um caixa especial já foi chamado.
Definition at line 37 of file Supermercado.h.
ListaCircular* Projeto1::Supermercado::caixas
Lista de caixas.
Definition at line 21 of file Supermercado.h.
int Projeto1::Supermercado::desistencias
Número de clientes que desistiram.
Definition at line 29 of file Supermercado.h.
int Projeto1::Supermercado::faturamentoBruto
Faturamento bruto do supermercado.
Definition at line 31 of file Supermercado.h.
int Projeto1::Supermercado::limiteCaixaEspecial
Limite para chamar um caixa especial.
Definition at line 35 of file Supermercado.h.
char* Projeto1::Supermercado::nomeSupermercado
Nome do supermercado.
Definition at line 23 of file Supermercado.h.
int Projeto1::Supermercado::tempoMedioClientes
Tempo medio de chegada de clientes.
Definition at line 25 of file Supermercado.h.
int Projeto1::Supermercado::tempoSimulacao
Tempo de Simulação.
Definition at line 27 of file Supermercado.h.
int Projeto1::Supermercado::valorDesistencias
Prejuiso gerado pelas desistências.
Definition at line 33 of file Supermercado.h.
The documentation for this class was generated from the following files:
/home/will/Programming/C++/ED/Projeto 1/src/Supermercado.h
/home/will/Programming/C++/ED/Projeto 1/src/Supermercado.cpp