FilaEncadeada: CabecaDeFila Class Reference
CabecaDeFila Class Reference
#include <CabecaDeFila.h>
Public Member Functions
CabecaDeFila ()
virtual ~CabecaDeFila ()
int enfileirar (InfoFila *dado)
InfoFila * desenfileirar ()
void limpar ()
Public Attributes
ElementoDeFila * primeiro
ElementoDeFila * ultimo
int tamanho
Private Member Functions
bool vazia ()
Detailed Description
Classe que modela uma Fila Encadeada.
As filas são estruturas baseadas no princípio FIFO (first in, first out), em que os elementos que foram inseridos no início são os primeiros a serem removidos. Uma fila possui duas funções básicas: Enfileirar(ENQUEUE), que adiciona um elemento ao final da fila, e Desenfileirar(DEQUEUE), que remove o elemento no início da fila. A operação Desenfileirar(DEQUEUE) só pode ser aplicado se a fila não estiver vazia, causando um erro de underflow ou fila vazia se esta operação for realizada nesta situação.
Para mais informações acesse: http://pt.wikipedia.org/wiki/FIFO
Definition at line 48 of file CabecaDeFila.h.
Constructor & Destructor Documentation
CabecaDeFila::CabecaDeFila ()
Método que constri um objeto que representa uma fila encadeado.
Definition at line 14 of file CabecaDeFila.cpp.
References primeiro, tamanho, and ultimo.
CabecaDeFila::~CabecaDeFila () [virtual]
Destrutor que exclui uma fila encadeada.
Para isso utiliza o método limpar.
Definition at line 26 of file CabecaDeFila.cpp.
References limpar().
Member Function Documentation
InfoFila * CabecaDeFila::desenfileirar ()
Método que remove um elemento da Fila. Primeiramente testa se a Fila possui elementos. Caso possua ele remove o primeiro elemento, ou seja o primeiro que foi inserido.
Returns:
0(NULL) = caso a Fila não possua elementos.
InfoFila = objeto que possui as informações do elemento removido.
Definition at line 64 of file CabecaDeFila.cpp.
References FILA_VAZIA, ElementoDeFila::info, primeiro, ElementoDeFila::proximo, tamanho, ultimo, and vazia().
Referenced by lerCasoDeTeste(), and mostrarMenuPrincipal().
int CabecaDeFila::enfileirar (InfoFila * dado)
Método que adiciona um elemento da fila.
Primeiramente teste se ainda é possivel adicionar um elemento à fila. Caso isso não seja verdadeiro ele retorna uma constante FILA_CHEIA.
Parameters:
InfoFila *dado= ponteiro para um objeto da classe InfoFila.
Returns:
FILA_CHEIA = constante que representa a falta de espaço na Fila.
tamanho = inteiro que informa a posição onde o dado foi inserido.
Definition at line 40 of file CabecaDeFila.cpp.
References FILA_CHEIA, InfoFila::mostrar(), primeiro, ElementoDeFila::proximo, tamanho, ultimo, and vazia().
Referenced by lerCasoDeTeste(), and mostrarMenuPrincipal().
void CabecaDeFila::limpar ()
Método que exclui todos os elementos da fila e suas respectivas informações, representado pela classe InfoLista.
Definition at line 94 of file CabecaDeFila.cpp.
References FILA_VAZIA, ElementoDeFila::info, primeiro, ElementoDeFila::proximo, and tamanho.
Referenced by mostrarMenuPrincipal(), and ~CabecaDeFila().
bool CabecaDeFila::vazia () [private]
Metodo que testa se a fila possui elementos.
Returns:
true = caso a Fila esteja vazia.
Definition at line 87 of file CabecaDeFila.cpp.
References FILA_VAZIA, and tamanho.
Referenced by desenfileirar(), and enfileirar().
Member Data Documentation
ElementoDeFila* CabecaDeFila::primeiro
Definition at line 52 of file CabecaDeFila.h.
Referenced by CabecaDeFila(), desenfileirar(), enfileirar(), and limpar().
int CabecaDeFila::tamanho
Definition at line 53 of file CabecaDeFila.h.
Referenced by CabecaDeFila(), desenfileirar(), enfileirar(), limpar(), and vazia().
ElementoDeFila * CabecaDeFila::ultimo
Definition at line 52 of file CabecaDeFila.h.
Referenced by CabecaDeFila(), desenfileirar(), and enfileirar().
The documentation for this class was generated from the following files:
src/CabecaDeFila.h
src/CabecaDeFila.cpp